name: levelup
publish_to: 'none'
description: LevelUp MVP — Flutter + Firebase
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  # Firebase
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.1
  # State & utils
  flutter_riverpod: ^2.5.1
  intl: ^0.19.0
  firebase_storage: ^12.3.1
  image_picker: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
