// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0h6fhTrTSGVi6llLDw1cWG7tq1JcitM8',
    appId: '1:209844004772:web:2e99ce26f2a0c94af94331',
    messagingSenderId: '209844004772',
    projectId: 'levelup-32d9b',
    authDomain: 'levelup-32d9b.firebaseapp.com',
    storageBucket: 'levelup-32d9b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWAMbta5DzBZeouMHkpR6B5iqjmKeCYzw',
    appId: '1:209844004772:android:9d448b87cc1046b9f94331',
    messagingSenderId: '209844004772',
    projectId: 'levelup-32d9b',
    storageBucket: 'levelup-32d9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4JyDOoPMDKy2JotTzyTI1jQA-WYN9wEc',
    appId: '1:209844004772:ios:8934f0948ae3269df94331',
    messagingSenderId: '209844004772',
    projectId: 'levelup-32d9b',
    storageBucket: 'levelup-32d9b.firebasestorage.app',
    iosBundleId: 'com.example.levelup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4JyDOoPMDKy2JotTzyTI1jQA-WYN9wEc',
    appId: '1:209844004772:ios:8934f0948ae3269df94331',
    messagingSenderId: '209844004772',
    projectId: 'levelup-32d9b',
    storageBucket: 'levelup-32d9b.firebasestorage.app',
    iosBundleId: 'com.example.levelup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0h6fhTrTSGVi6llLDw1cWG7tq1JcitM8',
    appId: '1:209844004772:web:e39b128a7d1ecf5ff94331',
    messagingSenderId: '209844004772',
    projectId: 'levelup-32d9b',
    authDomain: 'levelup-32d9b.firebaseapp.com',
    storageBucket: 'levelup-32d9b.firebasestorage.app',
  );
}
